"""attendance table 1

Revision ID: 1a3f71899313
Revises: 7a0ac6300fc4
Create Date: 2023-07-03 11:06:45.495461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3f71899313'
down_revision = '7a0ac6300fc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendanceuser', 'employeemodel', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendanceuser', type_='foreignkey')
    # ### end Alembic commands ###
