"""update status

Revision ID: 1fb778e05228
Revises: af582ce7c76d
Create Date: 2023-07-02 18:32:49.255481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb778e05228'
down_revision = 'af582ce7c76d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeecompany', sa.Column('status', sa.Enum('INIT', 'INVITED', 'ACCEPTED', 'REJECTED', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employeecompany', 'status')
    # ### end Alembic commands ###
