"""leave request

Revision ID: 380ca5e4e50d
Revises: 3060c5282721
Create Date: 2023-07-19 22:46:13.502797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380ca5e4e50d'
down_revision = '3060c5282721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.add_column('leaverequest', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('leaverequest', 'end_tate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaverequest', sa.Column('end_tate', sa.DATE(), nullable=True))
    op.drop_column('leaverequest', 'end_date')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
