"""init

Revision ID: 5a00b07dd896
Revises: fb7b0664a2d7
Create Date: 2023-08-16 20:04:55.044042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a00b07dd896'
down_revision = 'fb7b0664a2d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('remituser', sa.Column('refrence_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remituser', 'refrence_id')
    op.create_table('banners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_banners_id', 'banners', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('employeemodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('login_time', sa.TIME(), nullable=True),
    sa.Column('logout_time', sa.TIME(), nullable=True),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.Column('duty_time', sa.TIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('is_approver', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('total_sick_leave_taken', sa.INTEGER(), nullable=True),
    sa.Column('total_casual_leave_taken', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'phone', name='uq_company_employee')
    )
    op.create_index('ix_employeemodel_id', 'employeemodel', ['id'], unique=False)
    op.create_table('companymodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('established_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('total_casual_leave_in_year', sa.INTEGER(), nullable=True),
    sa.Column('total_sick_leave_in_year', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_companymodel_id', 'companymodel', ['id'], unique=False)
    op.create_table('attendanceuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.BIGINT(), nullable=True),
    sa.Column('photoUrl', sa.VARCHAR(length=256), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_employer', sa.BOOLEAN(), nullable=True),
    sa.Column('is_approver', sa.BOOLEAN(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_attendanceuser_id', 'attendanceuser', ['id'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=256), nullable=False),
    sa.Column('phone', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_id', 'otp', ['id'], unique=False)
    op.create_table('foreignexchangecharge',
    sa.Column('min_amount', sa.FLOAT(), nullable=False),
    sa.Column('is_flat', sa.BOOLEAN(), nullable=False),
    sa.Column('charge_upto_one_lakh', sa.FLOAT(), nullable=True),
    sa.Column('carge_from_one_ten_lakh', sa.FLOAT(), nullable=True),
    sa.Column('charge_from_ten_lakh_to_1core', sa.FLOAT(), nullable=True),
    sa.Column('charge_upto_one_lakh_in_percentage', sa.FLOAT(), nullable=True),
    sa.Column('charge_from_one_ten_lakh_in_percentage', sa.FLOAT(), nullable=True),
    sa.Column('charge_from_ten_lakh_to_1core_in_percentage', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('cancellation_charge', sa.FLOAT(), nullable=False),
    sa.Column('issuance_charge', sa.FLOAT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendancemodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('attendance_date', sa.DATE(), nullable=True),
    sa.Column('login_time', sa.TIME(), nullable=False),
    sa.Column('logout_time', sa.TIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_date', 'employee_id', 'company_id', name='uq_attendance_date_company_employee')
    )
    op.create_index('ix_attendancemodel_id', 'attendancemodel', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('breakmodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('break_start', sa.TIME(), nullable=True),
    sa.Column('break_end', sa.TIME(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('attendance_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendancemodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['employeemodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breakmodel_id', 'breakmodel', ['id'], unique=False)
    op.create_table('hero',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('nationality', sa.VARCHAR(), nullable=False),
    sa.Column('profile_type', sa.VARCHAR(), nullable=False),
    sa.Column('status_of_residence', sa.VARCHAR(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(), nullable=True),
    sa.Column('business_registered_number', sa.VARCHAR(), nullable=True),
    sa.Column('passport_number', sa.VARCHAR(), nullable=True),
    sa.Column('referal_code', sa.VARCHAR(), nullable=True),
    sa.Column('profession', sa.VARCHAR(), nullable=True),
    sa.Column('residence_type', sa.VARCHAR(), nullable=True),
    sa.Column('organization_type', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['remituser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remitotp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('otp_code', sa.VARCHAR(), nullable=False),
    sa.Column('phoneOrEmail', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employeecompany',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('is_invited', sa.BOOLEAN(), nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employeecompany_id', 'employeecompany', ['id'], unique=False)
    op.create_table('kyc',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('front_img', sa.VARCHAR(), nullable=True),
    sa.Column('back_img', sa.VARCHAR(), nullable=True),
    sa.Column('tilted_img', sa.VARCHAR(), nullable=True),
    sa.Column('selfie_img', sa.VARCHAR(), nullable=True),
    sa.Column('user_title', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('nationality', sa.VARCHAR(), nullable=False),
    sa.Column('intended_use_of_account', sa.VARCHAR(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('date_of_issue', sa.VARCHAR(), nullable=True),
    sa.Column('peroid_of_stay', sa.VARCHAR(), nullable=False),
    sa.Column('expire_date', sa.VARCHAR(), nullable=False),
    sa.Column('postal', sa.VARCHAR(), nullable=False),
    sa.Column('prefecture', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('street_address', sa.VARCHAR(), nullable=True),
    sa.Column('building_name', sa.VARCHAR(), nullable=True),
    sa.Column('expiry_date', sa.VARCHAR(), nullable=True),
    sa.Column('annual_income', sa.VARCHAR(), nullable=True),
    sa.Column('source_of_income', sa.VARCHAR(), nullable=True),
    sa.Column('tax_return', sa.VARCHAR(), nullable=True),
    sa.Column('home_contact_number', sa.VARCHAR(), nullable=False),
    sa.Column('emergency_contact_number', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['remituser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionstate',
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('reciving_method', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_method_id', sa.VARCHAR(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(), nullable=False),
    sa.Column('deposit_method', sa.VARCHAR(), nullable=False),
    sa.Column('deposit_id', sa.VARCHAR(), nullable=False),
    sa.Column('deposit_date', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaverequest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('leave_type', sa.VARCHAR(length=8), nullable=True),
    sa.Column('leave_day_type', sa.VARCHAR(length=7), nullable=True),
    sa.Column('document', sa.VARCHAR(length=256), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=256), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leaverequest_id', 'leaverequest', ['id'], unique=False)
    # ### end Alembic commands ###
