"""status added in employee company

Revision ID: 82073caf841c
Revises: 2d96eab589e7
Create Date: 2023-07-02 17:56:03.799144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82073caf841c'
down_revision = '2d96eab589e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeecompany', sa.Column('status', sa.Enum(('INIT', 'INIT'), ('INVITED', 'INVITED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employeecompany', 'status')
    # ### end Alembic commands ###
