"""employee updated

Revision ID: adbae44fdbca
Revises: 
Create Date: 2023-07-04 22:13:26.421571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbae44fdbca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.create_foreign_key(None, 'attendanceuser', 'employeemodel', ['employee_id'], ['id'])
    op.add_column('employeemodel', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('employeemodel', sa.Column('end_time', sa.Time(), nullable=True))
    op.drop_column('employeemodel', 'logout_time')
    op.drop_column('employeemodel', 'login_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeemodel', sa.Column('login_time', sa.TIME(), nullable=True))
    op.add_column('employeemodel', sa.Column('logout_time', sa.TIME(), nullable=True))
    op.drop_column('employeemodel', 'end_time')
    op.drop_column('employeemodel', 'start_time')
    op.drop_constraint(None, 'attendanceuser', type_='foreignkey')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
