"""update status

Revision ID: af582ce7c76d
Revises: 82073caf841c
Create Date: 2023-07-02 18:32:21.008790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af582ce7c76d'
down_revision = '82073caf841c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employeecompany', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeecompany', sa.Column('status', sa.VARCHAR(length=2), nullable=True))
    # ### end Alembic commands ###
