"""employee updated

Revision ID: b5ce94274a85
Revises: 
Create Date: 2023-07-05 22:16:38.511671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce94274a85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendanceuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('photoUrl', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_employer', sa.Boolean(), nullable=True),
    sa.Column('is_approver', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_attendanceuser_id'), 'attendanceuser', ['id'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_id'), 'otp', ['id'], unique=False)
    op.create_table('companymodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companymodel_id'), 'companymodel', ['id'], unique=False)
    op.create_table('employeemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('login_time', sa.Time(), nullable=True),
    sa.Column('logout_time', sa.Time(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('duty_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'phone', name='uq_company_employee')
    )
    op.create_index(op.f('ix_employeemodel_id'), 'employeemodel', ['id'], unique=False)
    op.create_table('attendancemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('login_time', sa.Time(), nullable=False),
    sa.Column('logout_time', sa.Time(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_date', 'employee_id', 'company_id', name='uq_attendance_date_company_employee')
    )
    op.create_index(op.f('ix_attendancemodel_id'), 'attendancemodel', ['id'], unique=False)
    op.create_table('employeecompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_invited', sa.Boolean(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'INVITED', 'ACCEPTED', 'REJECTED', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeecompany_id'), 'employeecompany', ['id'], unique=False)
    op.create_table('breakmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendancemodel.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakmodel_id'), 'breakmodel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breakmodel_id'), table_name='breakmodel')
    op.drop_table('breakmodel')
    op.drop_index(op.f('ix_employeecompany_id'), table_name='employeecompany')
    op.drop_table('employeecompany')
    op.drop_index(op.f('ix_attendancemodel_id'), table_name='attendancemodel')
    op.drop_table('attendancemodel')
    op.drop_index(op.f('ix_employeemodel_id'), table_name='employeemodel')
    op.drop_table('employeemodel')
    op.drop_index(op.f('ix_companymodel_id'), table_name='companymodel')
    op.drop_table('companymodel')
    op.drop_index(op.f('ix_otp_id'), table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_attendanceuser_id'), table_name='attendanceuser')
    op.drop_table('attendanceuser')
    # ### end Alembic commands ###
