"""attendance table upgrade

Revision ID: d97a6b5ff3fb
Revises: 
Create Date: 2023-07-05 11:58:07.353567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97a6b5ff3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(256), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_table('companymodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companymodel_id'), 'companymodel', ['id'], unique=False)
    op.create_table('employeemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('login_time', sa.Time(), nullable=True),
    sa.Column('logout_time', sa.Time(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('duty_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['attendanceuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeemodel_id'), 'employeemodel', ['id'], unique=False)
    op.create_table('attendancemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('login_time', sa.Time(), nullable=False),
    sa.Column('logout_time', sa.Time(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_date', 'employee_id', 'company_id', name='uq_attendance_date_company_employee')
    )
    op.create_index(op.f('ix_attendancemodel_id'), 'attendancemodel', ['id'], unique=False)
    op.create_table('employeecompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_invited', sa.Boolean(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('INIT', 'INVITED', 'ACCEPTED', 'REJECTED', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companymodel.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeecompany_id'), 'employeecompany', ['id'], unique=False)
    op.create_table('breakmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendancemodel.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['employeemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakmodel_id'), 'breakmodel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breakmodel_id'), table_name='breakmodel')
    op.drop_table('breakmodel')
    op.drop_index(op.f('ix_employeecompany_id'), table_name='employeecompany')
    op.drop_table('employeecompany')
    op.drop_index(op.f('ix_attendancemodel_id'), table_name='attendancemodel')
    op.drop_table('attendancemodel')
    op.drop_index(op.f('ix_employeemodel_id'), table_name='employeemodel')
    op.drop_table('employeemodel')
    op.drop_index(op.f('ix_companymodel_id'), table_name='companymodel')
    op.drop_table('companymodel')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
