"""l

Revision ID: e0807ca72c2c
Revises: 
Create Date: 2023-07-27 21:18:51.380506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0807ca72c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'leaverequest', 'companymodel', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaverequest', type_='foreignkey')
    # ### end Alembic commands ###
